import os
import sys
import json
import pandas as pd
import plotly.express as px
from datetime import date, datetime
from sqlalchemy import create_engine
from dotenv import load_dotenv

# ==========================================
# 1. SETUP & SECURE DATABASE CONNECTION
# ==========================================
load_dotenv()

def get_db_engine():
    user     = os.getenv("DB_USER",     "root")
    password = os.getenv("DB_PASSWORD", "samka1234")
    host     = os.getenv("DB_HOST",     "localhost")
    database = os.getenv("DB_NAME",     "mydb")
    return create_engine(f"mysql+pymysql://{user}:{password}@{host}/{database}")

engine = get_db_engine()

# ==========================================
# 2. UTILITIES
# ==========================================

def save_json_to_text(data, filename="sales_employee_output.txt"):
    try:
        path = os.path.join(os.path.dirname(os.path.abspath(__file__)), filename)
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4)
    except Exception as e:
        print(f"FAILED TO SAVE TEXT FILE: {e}", file=sys.stderr)

def verify_employee(user_id):
    """Validates that the user_id exists in the database before running queries."""
    query = f"SELECT emp_id, First_Name, Last_Name, role FROM employee WHERE emp_id = {user_id}"
    df    = pd.read_sql(query, engine)
    if df.empty:
        raise ValueError(f"Access Denied: Employee ID {user_id} not found.")
    return df.iloc[0].to_dict()

def safe_to_dict(df):
    if df.empty:
        return []
    # Handle numpy datetime64 columns
    for col in df.select_dtypes(include=['datetime64']).columns:
        df[col] = df[col].astype(str)
    # Handle object columns containing Python date/datetime instances
    for col in df.select_dtypes(include=['object']).columns:
        df[col] = df[col].apply(
            lambda x: x.isoformat() if isinstance(x, (date, datetime)) else x
        )
    return df.where(pd.notnull(df), None).to_dict(orient='records')

def evaluate_warnings(data, metric_key, threshold, condition='less', alert_msg="Alert"):
    warnings = []
    for row in data:
        val = row.get(metric_key)
        if val is None or (isinstance(val, float) and pd.isna(val)):
            continue
        try:
            fval = float(val)
        except (TypeError, ValueError):
            continue
        if condition == 'less' and fval < threshold:
            warnings.append(f"WARNING: {alert_msg} ({val})")
        elif condition == 'greater' and fval > threshold:
            warnings.append(f"WARNING: {alert_msg} ({val})")
    return warnings

def generate_chart(df, chart_type, title, x=None, y=None, names=None, values=None, color=None):
    if df.empty:
        return None
    df_plot = df.copy()
    for col in [x, names]:
        if col and col in df_plot.columns and df_plot[col].dtype in ['int64', 'float64'] and 'id' in col.lower():
            df_plot[col] = df_plot[col].astype(str)
    try:
        if   chart_type == 'bar':  fig = px.bar(df_plot,  x=x,     y=y,     color=color, title=title)
        elif chart_type == 'pie':  fig = px.pie(df_plot,  names=names, values=values, color=color, title=title)
        elif chart_type == 'line': fig = px.line(df_plot, x=x,     y=y,     color=color, title=title)
        else: return None
        return json.loads(fig.to_json())
    except Exception:
        return None

# ==========================================
# 3. INDIVIDUAL SALES EMPLOYEE METRICS
# (Strictly scoped to this employee's own data)
# ==========================================

def get_my_personal_info(uid):
    """Employee's personal profile and assigned branch."""
    verify_employee(uid)
    query = f"""
        SELECT emp_id, First_Name, Last_Name, role, salary, phone, birth,
               departement_id, branch_id
        FROM employee WHERE emp_id = {uid}
    """
    df = pd.read_sql(query, engine)
    return {"data": safe_to_dict(df), "warnings": [], "chart": None}

def get_my_total_sales_revenue(uid):
    """Total all-time revenue generated by this employee."""
    verify_employee(uid)
    query = f"SELECT SUM(price) as my_total_revenue FROM employee_sales_log WHERE employee_id = {uid}"
    df    = pd.read_sql(query, engine)
    data  = safe_to_dict(df.round(2))
    warnings = evaluate_warnings(
        data, 'my_total_revenue', 1000, 'less',
        "You are currently below your sales target!"
    )
    return {"data": data, "warnings": warnings, "chart": None}

def get_my_monthly_revenue(uid):
    """Revenue for the current month only."""
    verify_employee(uid)
    query = f"""
        SELECT SUM(price) as my_monthly_revenue, COUNT(record_id) as monthly_transactions
        FROM employee_sales_log
        WHERE employee_id = {uid}
          AND YEAR(transaction_date)  = YEAR(CURDATE())
          AND MONTH(transaction_date) = MONTH(CURDATE())
    """
    df   = pd.read_sql(query, engine)
    data = safe_to_dict(df.round(2))
    return {"data": data, "warnings": [], "chart": None}

def get_my_total_units_sold(uid):
    """Total units sold by this employee (all time)."""
    verify_employee(uid)
    query = f"SELECT SUM(amount) as my_total_units FROM employee_sales_log WHERE employee_id = {uid}"
    df    = pd.read_sql(query, engine)
    return {"data": safe_to_dict(df), "warnings": [], "chart": None}

def get_my_average_deal_size(uid):
    """Average transaction value for this employee."""
    verify_employee(uid)
    query = f"SELECT AVG(price) as my_avg_deal_size FROM employee_sales_log WHERE employee_id = {uid}"
    df    = pd.read_sql(query, engine)
    return {"data": safe_to_dict(df.round(2)), "warnings": [], "chart": None}

def get_my_top_products(uid):
    """Top 5 products by revenue for this employee."""
    verify_employee(uid)
    query = f"""
        SELECT p.name, p.model,
               SUM(esl.amount) as units_sold,
               SUM(esl.price)  as revenue_generated
        FROM employee_sales_log esl
        JOIN product_sold_log psl ON esl.record_id  = psl.record_id
        JOIN product p            ON psl.product_id = p.product_id
        WHERE esl.employee_id = {uid}
        GROUP BY p.product_id, p.name, p.model
        ORDER BY revenue_generated DESC LIMIT 5
    """
    df    = pd.read_sql(query, engine)
    chart = generate_chart(df, 'bar', 'My Top Products by Revenue',
                           x='name', y='revenue_generated')
    return {"data": safe_to_dict(df.round(2)), "warnings": [], "chart": chart}

def get_my_sales_trend(uid):
    """Monthly revenue trend for this employee over the last 12 months."""
    verify_employee(uid)
    query = f"""
        SELECT CONCAT(YEAR(transaction_date), '-',
                      LPAD(MONTH(transaction_date), 2, '0')) as month,
               SUM(price)  as revenue,
               SUM(amount) as units
        FROM employee_sales_log
        WHERE employee_id = {uid}
          AND transaction_date >= DATE_SUB(CURDATE(), INTERVAL 12 MONTH)
        GROUP BY month ORDER BY month ASC
    """
    df    = pd.read_sql(query, engine)
    chart = generate_chart(df, 'line', 'My 12-Month Revenue Trend', x='month', y='revenue')
    return {"data": safe_to_dict(df.round(2)), "warnings": [], "chart": chart}

def get_my_recent_transactions(uid):
    """Last 10 transactions for this employee."""
    verify_employee(uid)
    query = f"""
        SELECT esl.record_id, esl.transaction_date,
               p.name as product_name, esl.amount, esl.price
        FROM employee_sales_log esl
        JOIN product_sold_log psl ON esl.record_id  = psl.record_id
        JOIN product p            ON psl.product_id = p.product_id
        WHERE esl.employee_id = {uid}
        ORDER BY esl.transaction_date DESC LIMIT 10
    """
    df = pd.read_sql(query, engine)
    return {"data": safe_to_dict(df), "warnings": [], "chart": None}

# ==========================================
# 4. EXECUTION WRAPPER
# ==========================================

def run_all_sales_employee_metrics(user_id):
    """Executes all metrics for a single Sales Representative."""
    results        = {}
    employee_funcs = [
        get_my_personal_info,
        get_my_total_sales_revenue,
        get_my_monthly_revenue,
        get_my_total_units_sold,
        get_my_average_deal_size,
        get_my_top_products,
        get_my_sales_trend,
        get_my_recent_transactions,
    ]
    for func in employee_funcs:
        try:
            results[func.__name__] = func(user_id)
        except Exception as e:
            results[func.__name__] = {"data": [], "warnings": [f"Error: {str(e)}"], "chart": None}
    return results

# ==========================================
# 5. NODE.JS EXECUTION BRIDGE
# ==========================================
if __name__ == "__main__":
    try:
        emp_id  = int(sys.argv[1]) if len(sys.argv) > 1 else 3286
        results = run_all_sales_employee_metrics(emp_id)
        save_json_to_text(results, "sales_employee_output.txt")
        print(json.dumps(results, indent=4))
    except Exception as e:
        err = {"error": str(e)}
        save_json_to_text(err, "sales_employee_error_log.txt")
        print(json.dumps(err, indent=4))